// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -package usecase -source contract.go -destination contract_mock.go
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	domain "github.com/qsoulior/tech-generator/backend/internal/usecase/task_get_by_id/domain"
	gomock "go.uber.org/mock/gomock"
)

// MocktaskRepository is a mock of taskRepository interface.
type MocktaskRepository struct {
	ctrl     *gomock.Controller
	recorder *MocktaskRepositoryMockRecorder
	isgomock struct{}
}

// MocktaskRepositoryMockRecorder is the mock recorder for MocktaskRepository.
type MocktaskRepositoryMockRecorder struct {
	mock *MocktaskRepository
}

// NewMocktaskRepository creates a new mock instance.
func NewMocktaskRepository(ctrl *gomock.Controller) *MocktaskRepository {
	mock := &MocktaskRepository{ctrl: ctrl}
	mock.recorder = &MocktaskRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktaskRepository) EXPECT() *MocktaskRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MocktaskRepository) GetByID(ctx context.Context, id int64) (*domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MocktaskRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MocktaskRepository)(nil).GetByID), ctx, id)
}

// MockversionRepository is a mock of versionRepository interface.
type MockversionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockversionRepositoryMockRecorder
	isgomock struct{}
}

// MockversionRepositoryMockRecorder is the mock recorder for MockversionRepository.
type MockversionRepositoryMockRecorder struct {
	mock *MockversionRepository
}

// NewMockversionRepository creates a new mock instance.
func NewMockversionRepository(ctrl *gomock.Controller) *MockversionRepository {
	mock := &MockversionRepository{ctrl: ctrl}
	mock.recorder = &MockversionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockversionRepository) EXPECT() *MockversionRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockversionRepository) GetByID(ctx context.Context, id int64) (*domain.Version, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Version)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockversionRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockversionRepository)(nil).GetByID), ctx, id)
}

// MockresultRepository is a mock of resultRepository interface.
type MockresultRepository struct {
	ctrl     *gomock.Controller
	recorder *MockresultRepositoryMockRecorder
	isgomock struct{}
}

// MockresultRepositoryMockRecorder is the mock recorder for MockresultRepository.
type MockresultRepositoryMockRecorder struct {
	mock *MockresultRepository
}

// NewMockresultRepository creates a new mock instance.
func NewMockresultRepository(ctrl *gomock.Controller) *MockresultRepository {
	mock := &MockresultRepository{ctrl: ctrl}
	mock.recorder = &MockresultRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockresultRepository) EXPECT() *MockresultRepositoryMockRecorder {
	return m.recorder
}

// GetDataByID mocks base method.
func (m *MockresultRepository) GetDataByID(ctx context.Context, id int64) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDataByID", ctx, id)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDataByID indicates an expected call of GetDataByID.
func (mr *MockresultRepositoryMockRecorder) GetDataByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataByID", reflect.TypeOf((*MockresultRepository)(nil).GetDataByID), ctx, id)
}
