// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -package usecase -source contract.go -destination contract_mock.go
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	domain "github.com/qsoulior/tech-generator/backend/internal/service/version_create/domain"
	domain0 "github.com/qsoulior/tech-generator/backend/internal/usecase/version_create/domain"
	gomock "go.uber.org/mock/gomock"
)

// MocktemplateRepository is a mock of templateRepository interface.
type MocktemplateRepository struct {
	ctrl     *gomock.Controller
	recorder *MocktemplateRepositoryMockRecorder
	isgomock struct{}
}

// MocktemplateRepositoryMockRecorder is the mock recorder for MocktemplateRepository.
type MocktemplateRepositoryMockRecorder struct {
	mock *MocktemplateRepository
}

// NewMocktemplateRepository creates a new mock instance.
func NewMocktemplateRepository(ctrl *gomock.Controller) *MocktemplateRepository {
	mock := &MocktemplateRepository{ctrl: ctrl}
	mock.recorder = &MocktemplateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktemplateRepository) EXPECT() *MocktemplateRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MocktemplateRepository) GetByID(ctx context.Context, id int64) (*domain0.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain0.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MocktemplateRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MocktemplateRepository)(nil).GetByID), ctx, id)
}

// MockversionCreateService is a mock of versionCreateService interface.
type MockversionCreateService struct {
	ctrl     *gomock.Controller
	recorder *MockversionCreateServiceMockRecorder
	isgomock struct{}
}

// MockversionCreateServiceMockRecorder is the mock recorder for MockversionCreateService.
type MockversionCreateServiceMockRecorder struct {
	mock *MockversionCreateService
}

// NewMockversionCreateService creates a new mock instance.
func NewMockversionCreateService(ctrl *gomock.Controller) *MockversionCreateService {
	mock := &MockversionCreateService{ctrl: ctrl}
	mock.recorder = &MockversionCreateServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockversionCreateService) EXPECT() *MockversionCreateServiceMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockversionCreateService) Handle(ctx context.Context, in domain.VersionCreateIn) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, in)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockversionCreateServiceMockRecorder) Handle(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockversionCreateService)(nil).Handle), ctx, in)
}
