// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -package usecase -source contract.go -destination contract_mock.go
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	domain "github.com/qsoulior/tech-generator/backend/internal/usecase/user_create/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockuserRepository is a mock of userRepository interface.
type MockuserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockuserRepositoryMockRecorder
	isgomock struct{}
}

// MockuserRepositoryMockRecorder is the mock recorder for MockuserRepository.
type MockuserRepositoryMockRecorder struct {
	mock *MockuserRepository
}

// NewMockuserRepository creates a new mock instance.
func NewMockuserRepository(ctrl *gomock.Controller) *MockuserRepository {
	mock := &MockuserRepository{ctrl: ctrl}
	mock.recorder = &MockuserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserRepository) EXPECT() *MockuserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockuserRepository) Create(ctx context.Context, name, email string, password []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, name, email, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockuserRepositoryMockRecorder) Create(ctx, name, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockuserRepository)(nil).Create), ctx, name, email, password)
}

// ExistsByNameOrEmail mocks base method.
func (m *MockuserRepository) ExistsByNameOrEmail(ctx context.Context, name, email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByNameOrEmail", ctx, name, email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByNameOrEmail indicates an expected call of ExistsByNameOrEmail.
func (mr *MockuserRepositoryMockRecorder) ExistsByNameOrEmail(ctx, name, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByNameOrEmail", reflect.TypeOf((*MockuserRepository)(nil).ExistsByNameOrEmail), ctx, name, email)
}

// MockpasswordHasher is a mock of passwordHasher interface.
type MockpasswordHasher struct {
	ctrl     *gomock.Controller
	recorder *MockpasswordHasherMockRecorder
	isgomock struct{}
}

// MockpasswordHasherMockRecorder is the mock recorder for MockpasswordHasher.
type MockpasswordHasherMockRecorder struct {
	mock *MockpasswordHasher
}

// NewMockpasswordHasher creates a new mock instance.
func NewMockpasswordHasher(ctrl *gomock.Controller) *MockpasswordHasher {
	mock := &MockpasswordHasher{ctrl: ctrl}
	mock.recorder = &MockpasswordHasherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpasswordHasher) EXPECT() *MockpasswordHasherMockRecorder {
	return m.recorder
}

// Hash mocks base method.
func (m *MockpasswordHasher) Hash(password domain.Password) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hash", password)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hash indicates an expected call of Hash.
func (mr *MockpasswordHasherMockRecorder) Hash(password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hash", reflect.TypeOf((*MockpasswordHasher)(nil).Hash), password)
}
