// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -package service -source contract.go -destination contract_mock.go
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	domain "github.com/qsoulior/tech-generator/backend/internal/service/version_create/domain"
	gomock "go.uber.org/mock/gomock"
)

// MocktemplateRepository is a mock of templateRepository interface.
type MocktemplateRepository struct {
	ctrl     *gomock.Controller
	recorder *MocktemplateRepositoryMockRecorder
	isgomock struct{}
}

// MocktemplateRepositoryMockRecorder is the mock recorder for MocktemplateRepository.
type MocktemplateRepositoryMockRecorder struct {
	mock *MocktemplateRepository
}

// NewMocktemplateRepository creates a new mock instance.
func NewMocktemplateRepository(ctrl *gomock.Controller) *MocktemplateRepository {
	mock := &MocktemplateRepository{ctrl: ctrl}
	mock.recorder = &MocktemplateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktemplateRepository) EXPECT() *MocktemplateRepositoryMockRecorder {
	return m.recorder
}

// UpdateByID mocks base method.
func (m *MocktemplateRepository) UpdateByID(ctx context.Context, template domain.TemplateToUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", ctx, template)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MocktemplateRepositoryMockRecorder) UpdateByID(ctx, template any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MocktemplateRepository)(nil).UpdateByID), ctx, template)
}

// MockversionRepository is a mock of versionRepository interface.
type MockversionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockversionRepositoryMockRecorder
	isgomock struct{}
}

// MockversionRepositoryMockRecorder is the mock recorder for MockversionRepository.
type MockversionRepositoryMockRecorder struct {
	mock *MockversionRepository
}

// NewMockversionRepository creates a new mock instance.
func NewMockversionRepository(ctrl *gomock.Controller) *MockversionRepository {
	mock := &MockversionRepository{ctrl: ctrl}
	mock.recorder = &MockversionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockversionRepository) EXPECT() *MockversionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockversionRepository) Create(ctx context.Context, version domain.Version) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, version)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockversionRepositoryMockRecorder) Create(ctx, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockversionRepository)(nil).Create), ctx, version)
}

// MockvariableRepository is a mock of variableRepository interface.
type MockvariableRepository struct {
	ctrl     *gomock.Controller
	recorder *MockvariableRepositoryMockRecorder
	isgomock struct{}
}

// MockvariableRepositoryMockRecorder is the mock recorder for MockvariableRepository.
type MockvariableRepositoryMockRecorder struct {
	mock *MockvariableRepository
}

// NewMockvariableRepository creates a new mock instance.
func NewMockvariableRepository(ctrl *gomock.Controller) *MockvariableRepository {
	mock := &MockvariableRepository{ctrl: ctrl}
	mock.recorder = &MockvariableRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockvariableRepository) EXPECT() *MockvariableRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockvariableRepository) Create(ctx context.Context, variables []domain.VariableToCreate) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, variables)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockvariableRepositoryMockRecorder) Create(ctx, variables any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockvariableRepository)(nil).Create), ctx, variables)
}

// MockconstraintRepository is a mock of constraintRepository interface.
type MockconstraintRepository struct {
	ctrl     *gomock.Controller
	recorder *MockconstraintRepositoryMockRecorder
	isgomock struct{}
}

// MockconstraintRepositoryMockRecorder is the mock recorder for MockconstraintRepository.
type MockconstraintRepositoryMockRecorder struct {
	mock *MockconstraintRepository
}

// NewMockconstraintRepository creates a new mock instance.
func NewMockconstraintRepository(ctrl *gomock.Controller) *MockconstraintRepository {
	mock := &MockconstraintRepository{ctrl: ctrl}
	mock.recorder = &MockconstraintRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockconstraintRepository) EXPECT() *MockconstraintRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockconstraintRepository) Create(ctx context.Context, constraints []domain.ConstraintToCreate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, constraints)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockconstraintRepositoryMockRecorder) Create(ctx, constraints any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockconstraintRepository)(nil).Create), ctx, constraints)
}
