// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -package usecase -source contract.go -destination contract_mock.go
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	domain "github.com/qsoulior/tech-generator/backend/internal/usecase/folder_user_update/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockfolderRepository is a mock of folderRepository interface.
type MockfolderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockfolderRepositoryMockRecorder
	isgomock struct{}
}

// MockfolderRepositoryMockRecorder is the mock recorder for MockfolderRepository.
type MockfolderRepositoryMockRecorder struct {
	mock *MockfolderRepository
}

// NewMockfolderRepository creates a new mock instance.
func NewMockfolderRepository(ctrl *gomock.Controller) *MockfolderRepository {
	mock := &MockfolderRepository{ctrl: ctrl}
	mock.recorder = &MockfolderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfolderRepository) EXPECT() *MockfolderRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockfolderRepository) GetByID(ctx context.Context, id int64) (*domain.Folder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Folder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockfolderRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockfolderRepository)(nil).GetByID), ctx, id)
}

// MockfolderUserRepository is a mock of folderUserRepository interface.
type MockfolderUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockfolderUserRepositoryMockRecorder
	isgomock struct{}
}

// MockfolderUserRepositoryMockRecorder is the mock recorder for MockfolderUserRepository.
type MockfolderUserRepositoryMockRecorder struct {
	mock *MockfolderUserRepository
}

// NewMockfolderUserRepository creates a new mock instance.
func NewMockfolderUserRepository(ctrl *gomock.Controller) *MockfolderUserRepository {
	mock := &MockfolderUserRepository{ctrl: ctrl}
	mock.recorder = &MockfolderUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfolderUserRepository) EXPECT() *MockfolderUserRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockfolderUserRepository) Delete(ctx context.Context, folderID int64, userIDs []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, folderID, userIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockfolderUserRepositoryMockRecorder) Delete(ctx, folderID, userIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockfolderUserRepository)(nil).Delete), ctx, folderID, userIDs)
}

// GetByFolderID mocks base method.
func (m *MockfolderUserRepository) GetByFolderID(ctx context.Context, folderID int64) ([]domain.FolderUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByFolderID", ctx, folderID)
	ret0, _ := ret[0].([]domain.FolderUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByFolderID indicates an expected call of GetByFolderID.
func (mr *MockfolderUserRepositoryMockRecorder) GetByFolderID(ctx, folderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByFolderID", reflect.TypeOf((*MockfolderUserRepository)(nil).GetByFolderID), ctx, folderID)
}

// Upsert mocks base method.
func (m *MockfolderUserRepository) Upsert(ctx context.Context, folderID int64, users []domain.FolderUser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, folderID, users)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockfolderUserRepositoryMockRecorder) Upsert(ctx, folderID, users any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockfolderUserRepository)(nil).Upsert), ctx, folderID, users)
}

// MockuserRepository is a mock of userRepository interface.
type MockuserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockuserRepositoryMockRecorder
	isgomock struct{}
}

// MockuserRepositoryMockRecorder is the mock recorder for MockuserRepository.
type MockuserRepositoryMockRecorder struct {
	mock *MockuserRepository
}

// NewMockuserRepository creates a new mock instance.
func NewMockuserRepository(ctrl *gomock.Controller) *MockuserRepository {
	mock := &MockuserRepository{ctrl: ctrl}
	mock.recorder = &MockuserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserRepository) EXPECT() *MockuserRepositoryMockRecorder {
	return m.recorder
}

// GetByIDs mocks base method.
func (m *MockuserRepository) GetByIDs(ctx context.Context, ids []int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDs", ctx, ids)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDs indicates an expected call of GetByIDs.
func (mr *MockuserRepositoryMockRecorder) GetByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDs", reflect.TypeOf((*MockuserRepository)(nil).GetByIDs), ctx, ids)
}
