openapi: 3.0.4
info:
  title: tech-generator
  version: 0.0.1
paths:
  /project/create:
    post:
      summary: Создать проект
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProjectCreateRequest"
      responses:
        201:
          description: Created
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /project/delete/{projectID}:
    delete:
      summary: Удалить проект
      parameters:
        - $ref: "#/components/parameters/ProjectID"
      responses:
        204:
          description: No content
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /project/list:
    get:
      summary: Получить список проектов
      parameters:
        - $ref: "#/components/parameters/Page"
        - $ref: "#/components/parameters/Size"
        - $ref: "#/components/parameters/Sorting"
        - $ref: "#/components/parameters/ProjectName"
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProjectListResponse"
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /task/create:
    post:
      summary: Создать задачу генерации
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TaskCreateRequest"
      responses:
        201:
          description: Created
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /task/get/{taskID}:
    get:
      summary: Получить задачу генерации по ID
      parameters:
        - $ref: "#/components/parameters/TaskID"
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskGetByIDResponse"
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /task/list:
    get:
      summary: Получить список задач генерации
      parameters:
        - $ref: "#/components/parameters/Page"
        - $ref: "#/components/parameters/Size"
        - $ref: "#/components/parameters/Sorting"
        - $ref: "#/components/parameters/TaskVersionID"
        - $ref: "#/components/parameters/TaskCreatorID"
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskListResponse"
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /template/create:
    post:
      summary: Создать шаблон
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TemplateCreateRequest"
      responses:
        201:
          description: Created
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /template/delete/{templateID}:
    delete:
      summary: Удалить шаблон
      parameters:
        - $ref: "#/components/parameters/TemplateID"
      responses:
        204:
          description: No content
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /template/get/{templateID}:
    get:
      summary: Получить шаблон по ID
      parameters:
        - $ref: "#/components/parameters/TemplateID"
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TemplateGetByIDResponse"
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  parameters:
    Page:
      name: page
      description: Номер страницы
      in: query
      required: false
      schema:
        type: integer
        default: 1

    Size:
      name: size
      description: Количество записей на странице
      in: query
      required: false
      schema:
        type: integer
        default: 20

    Sorting:
      name: sorting
      description: Сортировка списка
      in: query
      required: false
      schema:
        type: object
        required:
          - attribute
          - direction
        properties:
          attribute:
            type: string
            description: Атрибут, по которому сортируется список
          direction:
            type: string
            description: Направление, по которому сортируется список
            enum:
              - ASC
              - DESC

    ProjectID:
      name: projectID
      description: ID проекта
      in: path
      required: true
      schema:
        type: integer

    ProjectName:
      name: projectName
      description: Название проекта
      in: query
      required: false
      schema:
        type: string

    TaskID:
      name: taskID
      description: ID задачи
      in: path
      required: true
      schema:
        type: integer

    TaskVersionID:
      name: versionID
      description: ID версии
      in: query
      required: true
      schema:
        type: integer

    TaskCreatorID:
      name: creatorID
      description: ID создателя задачи
      in: query
      required: false
      schema:
        type: integer

    TemplateID:
      name: templateID
      description: ID шаблона
      in: path
      required: true
      schema:
        type: integer

  schemas:
    Error:
      type: object
      description: Ошибка
      required:
        - message
      properties:
        message:
          type: string

    TaskStatus:
      type: string
      description: Статус задачи
      enum:
        - created
        - in_progress
        - succeed
        - failed

    ProjectCreateRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: Название проекта

    ProjectListResponse:
      type: object
      required:
        - projects
        - totalProjects
        - totalPages
      properties:
        projects:
          type: array
          description: Список проектов
          items:
            type: object
            description: Проект
            required:
              - id
              - name
              - authorName
            properties:
              id:
                type: integer
                description: ID проекта
              name:
                type: string
                description: Название проекта
              authorName:
                type: string
                description: Имя автора проекта
        totalProjects:
          type: integer
          description: Общее количество проектов
        totalPages:
          type: integer
          description: Общее количество страниц

    TaskCreateRequest:
      type: object
      required:
        - versionID
        - payload
      properties:
        versionID:
          type: integer
          description: ID версии шаблона
        payload:
          type: object
          description: Пэйлоад задачи
          additionalProperties: true

    TaskGetByIDResponse:
      type: object
      required:
        - task
      properties:
        task:
          type: object
          required:
            - id
            - versionID
            - status
            - payload
            - creatorName
            - createdAt
          properties:
            id:
              type: integer
              description: ID задачи
            versionID:
              type: integer
              description: ID версии
            status:
              $ref: "#/components/schemas/TaskStatus"
            payload:
              type: object
              description: Пэйлоад задачи
              additionalProperties: true
            error:
              type: object
              description: Ошибка обработки задачи
              nullable: true
              properties:
                message:
                  type: string
                  description: Сообщение ошибки
                variableErrors:
                  type: array
                  items:
                    type: object
                    description: Ошибка обработки переменных
                    required:
                      - id
                      - name
                    properties:
                      id:
                        type: integer
                        description: ID переменной
                      name:
                        type: string
                        description: Название переменной
                      message:
                        type: string
                        description: Сообщение ошибки
                      constraintErrors:
                        type: array
                        items:
                          type: object
                          description: Ошибка обработки ограничений
                          required:
                            - id
                            - name
                          properties:
                            id:
                              type: integer
                              description: ID ограничения
                            name:
                              type: string
                              description: Название ограничения
                            message:
                              type: string
                              description: Сообщение ошибки
            creatorName:
              type: string
              description: Имя создателя задачи
            createdAt:
              type: string
              format: date-time
              description: Дата и время создания задачи
            updatedAt:
              type: string
              format: date-time
              description: Дата и время обновления задачи
              nullable: true
        result:
          type: string

    TaskListResponse:
      type: object
      required:
        - tasks
        - totalTasks
        - totalPages
      properties:
        tasks:
          type: array
          description: Список задач генерации
          items:
            type: object
            description: Задача генерации
            required:
              - id
              - status
              - creatorName
              - createdAt
            properties:
              id:
                type: integer
                description: ID задачи генерации
              status:
                $ref: "#/components/schemas/TaskStatus"
              creatorName:
                type: string
                description: Имя создателя задачи
              createdAt:
                type: string
                format: date-time
                description: Дата и время создания задачи
              updatedAt:
                type: string
                format: date-time
                description: Дата и время обновления задачи
                nullable: true
        totalTasks:
          type: integer
          description: Общее количество задач
        totalPages:
          type: integer
          description: Общее количество страниц

    TemplateCreateRequest:
      type: object
      required:
        - name
        - projectID
      properties:
        name:
          type: string
          description: Название шаблона
        projectID:
          type: integer
          description: ID проекта

    TemplateGetByIDResponse:
      type: object
      required:
        - number
        - createdAt
        - data
        - variables
      properties:
        number:
          type: integer
          description: Номер последней версии шаблона
        createdAt:
          type: string
          format: date-time
          description: Дата и время создания версии
        data:
          type: string
          description: Данные шаблона
        variables:
          type: array
          description: Список переменных шаблона
          items:
            type: object
            description: Переменная шаблона
            required:
              - id
              - name
              - type
              - isInput
              - constraints
            properties:
              id:
                type: integer
                description: ID переменной
              name:
                type: string
                description: Название переменной
              type:
                type: string
                description: Тип переменной
                enum:
                  - string
                  - integer
                  - float
              expression:
                type: string
                description: Выражение переменной
                nullable: true
              isInput:
                type: boolean
                description: Являтеся ли переменная входной
              constraints:
                type: array
                description: Список ограничений переменной
                items:
                  type: object
                  description: Ограничение переменной
                  required:
                    - id
                    - name
                    - expression
                    - isActive
                  properties:
                    id:
                      type: integer
                      description: ID ограничения
                    name:
                      type: string
                      description: Название ограничения
                    expression:
                      type: string
                      description: Выражение ограничения
                    isActive:
                      type: boolean
                      description: Активно ли ограничение
