// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -package usecase -source contract.go -destination contract_mock.go
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	domain "github.com/qsoulior/tech-generator/backend/internal/usecase/template_list_default/domain"
	gomock "go.uber.org/mock/gomock"
)

// MocktemplateRepository is a mock of templateRepository interface.
type MocktemplateRepository struct {
	ctrl     *gomock.Controller
	recorder *MocktemplateRepositoryMockRecorder
	isgomock struct{}
}

// MocktemplateRepositoryMockRecorder is the mock recorder for MocktemplateRepository.
type MocktemplateRepositoryMockRecorder struct {
	mock *MocktemplateRepository
}

// NewMocktemplateRepository creates a new mock instance.
func NewMocktemplateRepository(ctrl *gomock.Controller) *MocktemplateRepository {
	mock := &MocktemplateRepository{ctrl: ctrl}
	mock.recorder = &MocktemplateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktemplateRepository) EXPECT() *MocktemplateRepositoryMockRecorder {
	return m.recorder
}

// GetTotalDefault mocks base method.
func (m *MocktemplateRepository) GetTotalDefault(ctx context.Context, in domain.TemplateListDefaultIn) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalDefault", ctx, in)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalDefault indicates an expected call of GetTotalDefault.
func (mr *MocktemplateRepositoryMockRecorder) GetTotalDefault(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalDefault", reflect.TypeOf((*MocktemplateRepository)(nil).GetTotalDefault), ctx, in)
}

// ListDefault mocks base method.
func (m *MocktemplateRepository) ListDefault(ctx context.Context, in domain.TemplateListDefaultIn) ([]domain.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDefault", ctx, in)
	ret0, _ := ret[0].([]domain.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDefault indicates an expected call of ListDefault.
func (mr *MocktemplateRepositoryMockRecorder) ListDefault(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDefault", reflect.TypeOf((*MocktemplateRepository)(nil).ListDefault), ctx, in)
}
