// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -package usecase -source contract.go -destination contract_mock.go
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	domain "github.com/qsoulior/tech-generator/backend/internal/usecase/version_list/domain"
	gomock "go.uber.org/mock/gomock"
)

// MocktemplateRepository is a mock of templateRepository interface.
type MocktemplateRepository struct {
	ctrl     *gomock.Controller
	recorder *MocktemplateRepositoryMockRecorder
	isgomock struct{}
}

// MocktemplateRepositoryMockRecorder is the mock recorder for MocktemplateRepository.
type MocktemplateRepositoryMockRecorder struct {
	mock *MocktemplateRepository
}

// NewMocktemplateRepository creates a new mock instance.
func NewMocktemplateRepository(ctrl *gomock.Controller) *MocktemplateRepository {
	mock := &MocktemplateRepository{ctrl: ctrl}
	mock.recorder = &MocktemplateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktemplateRepository) EXPECT() *MocktemplateRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MocktemplateRepository) GetByID(ctx context.Context, id int64) (*domain.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MocktemplateRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MocktemplateRepository)(nil).GetByID), ctx, id)
}

// MockversionRepository is a mock of versionRepository interface.
type MockversionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockversionRepositoryMockRecorder
	isgomock struct{}
}

// MockversionRepositoryMockRecorder is the mock recorder for MockversionRepository.
type MockversionRepositoryMockRecorder struct {
	mock *MockversionRepository
}

// NewMockversionRepository creates a new mock instance.
func NewMockversionRepository(ctrl *gomock.Controller) *MockversionRepository {
	mock := &MockversionRepository{ctrl: ctrl}
	mock.recorder = &MockversionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockversionRepository) EXPECT() *MockversionRepositoryMockRecorder {
	return m.recorder
}

// ListByTemplateID mocks base method.
func (m *MockversionRepository) ListByTemplateID(ctx context.Context, templateID int64) ([]domain.Version, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByTemplateID", ctx, templateID)
	ret0, _ := ret[0].([]domain.Version)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByTemplateID indicates an expected call of ListByTemplateID.
func (mr *MockversionRepositoryMockRecorder) ListByTemplateID(ctx, templateID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByTemplateID", reflect.TypeOf((*MockversionRepository)(nil).ListByTemplateID), ctx, templateID)
}
