version: "2"
linters:
  default: none
  enable:
    - errcheck # Errcheck is a program for checking for unchecked errors in Go code
    - gochecknoinits # Checks that no init functions are present in Go code
    - gosec # Inspects source code for security problems
    - govet # Examines Go source code and reports suspicious constructs
    - ineffassign # Detects when assignments to existing variables are not used
    - makezero # Finds slice declarations with non-zero initial length
    - revive # Fast, configurable, extensible, flexible, and beautiful linter for Go
    - staticcheck # It's a set of rules from staticcheck
    - unused # Checks Go code for unused constants, variables, functions and types
    - whitespace # Checks for unnecessary newlines at the start and end of functions, if, for, etc
  settings:
    revive:
      rules:
        - name: var-naming
          disabled: true
formatters:
  enable:
    - gci # Controls Go package import order and makes it always deterministic
    - gofumpt # Checks whether code was gofumpt-ed
  settings:
    gci:
      sections:
        - standard # Captures all standard packages
        - localmodule # Contains all local packages
        - default # Contains all imports that could not be matched to another section type
