// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -package usecase -source contract.go -destination contract_mock.go
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	domain "github.com/qsoulior/tech-generator/backend/internal/usecase/template_create/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockprojectRepository is a mock of projectRepository interface.
type MockprojectRepository struct {
	ctrl     *gomock.Controller
	recorder *MockprojectRepositoryMockRecorder
	isgomock struct{}
}

// MockprojectRepositoryMockRecorder is the mock recorder for MockprojectRepository.
type MockprojectRepositoryMockRecorder struct {
	mock *MockprojectRepository
}

// NewMockprojectRepository creates a new mock instance.
func NewMockprojectRepository(ctrl *gomock.Controller) *MockprojectRepository {
	mock := &MockprojectRepository{ctrl: ctrl}
	mock.recorder = &MockprojectRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockprojectRepository) EXPECT() *MockprojectRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockprojectRepository) GetByID(ctx context.Context, id int64) (*domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockprojectRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockprojectRepository)(nil).GetByID), ctx, id)
}

// MocktemplateRepository is a mock of templateRepository interface.
type MocktemplateRepository struct {
	ctrl     *gomock.Controller
	recorder *MocktemplateRepositoryMockRecorder
	isgomock struct{}
}

// MocktemplateRepositoryMockRecorder is the mock recorder for MocktemplateRepository.
type MocktemplateRepositoryMockRecorder struct {
	mock *MocktemplateRepository
}

// NewMocktemplateRepository creates a new mock instance.
func NewMocktemplateRepository(ctrl *gomock.Controller) *MocktemplateRepository {
	mock := &MocktemplateRepository{ctrl: ctrl}
	mock.recorder = &MocktemplateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktemplateRepository) EXPECT() *MocktemplateRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MocktemplateRepository) Create(ctx context.Context, template domain.Template) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, template)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MocktemplateRepositoryMockRecorder) Create(ctx, template any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MocktemplateRepository)(nil).Create), ctx, template)
}
