CREATE TABLE folder (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    parent_id BIGINT REFERENCES folder (id),
    name VARCHAR(100) NOT NULL,
    author_id BIGINT NOT NULL REFERENCES usr (id),
    root_author_id BIGINT NOT NULL REFERENCES usr (id)
);

CREATE INDEX folder__name__idx ON folder (name);

CREATE INDEX folder__author_id__idx ON folder (author_id);

CREATE INDEX folder__root_author_id__idx ON folder (root_author_id);

CREATE TABLE folder_user (
    folder_id BIGINT NOT NULL REFERENCES folder (id),
    user_id BIGINT NOT NULL REFERENCES usr (id),
    role VARCHAR(50) NOT NULL DEFAULT 'read',
    CHECK (role IN ('read', 'write', 'maintain')),
    PRIMARY KEY (folder_id, user_id)
);