CREATE TABLE project (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    author_id BIGINT NOT NULL REFERENCES usr (id)
);

CREATE INDEX project__name__idx ON project (name);

CREATE INDEX project__author_id__idx ON project (author_id);

CREATE TABLE project_user (
    project_id BIGINT NOT NULL REFERENCES project (id),
    user_id BIGINT NOT NULL REFERENCES usr (id),
    role VARCHAR(50) NOT NULL DEFAULT 'read',
    CHECK (role IN ('read', 'write', 'maintain')),
    PRIMARY KEY (project_id, user_id)
);

CREATE INDEX project_user__project_id__idx ON project_user (project_id);