CREATE TABLE template (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(200) NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    updated_at TIMESTAMP,
    project_id BIGINT REFERENCES project (id),
    author_id BIGINT REFERENCES usr (id),
    last_version_id BIGINT
);

CREATE INDEX template__name__idx ON template (name);

CREATE INDEX template__author_id__idx ON template (author_id);

CREATE TABLE template_user (
    template_id BIGINT NOT NULL REFERENCES template (id),
    user_id BIGINT NOT NULL REFERENCES usr (id),
    role VARCHAR(50) NOT NULL DEFAULT 'read',
    CHECK (role IN ('read', 'write')),
    PRIMARY KEY (template_id, user_id)
);