CREATE TABLE template_version (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    number BIGINT NOT NULL,
    template_id BIGINT NOT NULL REFERENCES template (id),
    author_id BIGINT REFERENCES usr (id),
    created_at TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    data BYTEA NOT NULL
);

CREATE INDEX template_version__template_id__idx ON template_version (template_id);