CREATE TABLE variable (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    version_id BIGINT NOT NULL REFERENCES template_version (id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(50) NOT NULL DEFAULT 'string',
    expression VARCHAR,
    is_input BOOLEAN NOT NULL,
    CHECK (type IN ('integer', 'float', 'string')),
    UNIQUE (version_id, name)
);

CREATE INDEX variable__version_id__idx ON variable (version_id);