CREATE TABLE variable_constraint (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    variable_id BIGINT NOT NULL REFERENCES variable (id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    expression VARCHAR NOT NULL,
    is_active BOOLEAN NOT NULL,
    UNIQUE (variable_id, name)
);

CREATE INDEX variable_constraint__variable_id__idx ON variable_constraint (variable_id);