CREATE TABLE task (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    version_id BIGINT NOT NULL REFERENCES template_version (id),
    status VARCHAR(50) NOT NULL DEFAULT 'created',
    payload jsonb NOT NULL,
    result_id BIGINT REFERENCES result (id),
    error jsonb,
    creator_id BIGINT NOT NULL REFERENCES usr (id),
    created_at TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    updated_at TIMESTAMP,
    CHECK (
        status IN ('created', 'in_progress', 'succeed', 'failed')
    )
);

CREATE INDEX task__version_id__idx ON task (version_id);
