// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -package usecase -source contract.go -destination contract_mock.go
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	domain "github.com/qsoulior/tech-generator/backend/internal/service/version_get/domain"
	domain0 "github.com/qsoulior/tech-generator/backend/internal/usecase/task_process/domain"
	gomock "go.uber.org/mock/gomock"
)

// MocktaskRepository is a mock of taskRepository interface.
type MocktaskRepository struct {
	ctrl     *gomock.Controller
	recorder *MocktaskRepositoryMockRecorder
	isgomock struct{}
}

// MocktaskRepositoryMockRecorder is the mock recorder for MocktaskRepository.
type MocktaskRepositoryMockRecorder struct {
	mock *MocktaskRepository
}

// NewMocktaskRepository creates a new mock instance.
func NewMocktaskRepository(ctrl *gomock.Controller) *MocktaskRepository {
	mock := &MocktaskRepository{ctrl: ctrl}
	mock.recorder = &MocktaskRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktaskRepository) EXPECT() *MocktaskRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MocktaskRepository) GetByID(ctx context.Context, id int64) (*domain0.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain0.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MocktaskRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MocktaskRepository)(nil).GetByID), ctx, id)
}

// UpdateByID mocks base method.
func (m *MocktaskRepository) UpdateByID(ctx context.Context, task domain0.TaskUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MocktaskRepositoryMockRecorder) UpdateByID(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MocktaskRepository)(nil).UpdateByID), ctx, task)
}

// MockversionGetService is a mock of versionGetService interface.
type MockversionGetService struct {
	ctrl     *gomock.Controller
	recorder *MockversionGetServiceMockRecorder
	isgomock struct{}
}

// MockversionGetServiceMockRecorder is the mock recorder for MockversionGetService.
type MockversionGetServiceMockRecorder struct {
	mock *MockversionGetService
}

// NewMockversionGetService creates a new mock instance.
func NewMockversionGetService(ctrl *gomock.Controller) *MockversionGetService {
	mock := &MockversionGetService{ctrl: ctrl}
	mock.recorder = &MockversionGetServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockversionGetService) EXPECT() *MockversionGetServiceMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockversionGetService) Handle(ctx context.Context, versionID int64) (*domain.Version, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, versionID)
	ret0, _ := ret[0].(*domain.Version)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockversionGetServiceMockRecorder) Handle(ctx, versionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockversionGetService)(nil).Handle), ctx, versionID)
}

// MockvariableProcessService is a mock of variableProcessService interface.
type MockvariableProcessService struct {
	ctrl     *gomock.Controller
	recorder *MockvariableProcessServiceMockRecorder
	isgomock struct{}
}

// MockvariableProcessServiceMockRecorder is the mock recorder for MockvariableProcessService.
type MockvariableProcessServiceMockRecorder struct {
	mock *MockvariableProcessService
}

// NewMockvariableProcessService creates a new mock instance.
func NewMockvariableProcessService(ctrl *gomock.Controller) *MockvariableProcessService {
	mock := &MockvariableProcessService{ctrl: ctrl}
	mock.recorder = &MockvariableProcessServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockvariableProcessService) EXPECT() *MockvariableProcessServiceMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockvariableProcessService) Handle(ctx context.Context, in domain0.VariableProcessIn) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, in)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockvariableProcessServiceMockRecorder) Handle(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockvariableProcessService)(nil).Handle), ctx, in)
}

// MockdataProcessService is a mock of dataProcessService interface.
type MockdataProcessService struct {
	ctrl     *gomock.Controller
	recorder *MockdataProcessServiceMockRecorder
	isgomock struct{}
}

// MockdataProcessServiceMockRecorder is the mock recorder for MockdataProcessService.
type MockdataProcessServiceMockRecorder struct {
	mock *MockdataProcessService
}

// NewMockdataProcessService creates a new mock instance.
func NewMockdataProcessService(ctrl *gomock.Controller) *MockdataProcessService {
	mock := &MockdataProcessService{ctrl: ctrl}
	mock.recorder = &MockdataProcessServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdataProcessService) EXPECT() *MockdataProcessServiceMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockdataProcessService) Handle(ctx context.Context, in domain0.DataProcessIn) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, in)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockdataProcessServiceMockRecorder) Handle(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockdataProcessService)(nil).Handle), ctx, in)
}
