// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -package usecase -source contract.go -destination contract_mock.go
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/qsoulior/tech-generator/backend/internal/usecase/user_token_create/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockuserRepository is a mock of userRepository interface.
type MockuserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockuserRepositoryMockRecorder
	isgomock struct{}
}

// MockuserRepositoryMockRecorder is the mock recorder for MockuserRepository.
type MockuserRepositoryMockRecorder struct {
	mock *MockuserRepository
}

// NewMockuserRepository creates a new mock instance.
func NewMockuserRepository(ctrl *gomock.Controller) *MockuserRepository {
	mock := &MockuserRepository{ctrl: ctrl}
	mock.recorder = &MockuserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserRepository) EXPECT() *MockuserRepositoryMockRecorder {
	return m.recorder
}

// GetByName mocks base method.
func (m *MockuserRepository) GetByName(ctx context.Context, name string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockuserRepositoryMockRecorder) GetByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockuserRepository)(nil).GetByName), ctx, name)
}

// MockpasswordVerifier is a mock of passwordVerifier interface.
type MockpasswordVerifier struct {
	ctrl     *gomock.Controller
	recorder *MockpasswordVerifierMockRecorder
	isgomock struct{}
}

// MockpasswordVerifierMockRecorder is the mock recorder for MockpasswordVerifier.
type MockpasswordVerifierMockRecorder struct {
	mock *MockpasswordVerifier
}

// NewMockpasswordVerifier creates a new mock instance.
func NewMockpasswordVerifier(ctrl *gomock.Controller) *MockpasswordVerifier {
	mock := &MockpasswordVerifier{ctrl: ctrl}
	mock.recorder = &MockpasswordVerifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpasswordVerifier) EXPECT() *MockpasswordVerifierMockRecorder {
	return m.recorder
}

// Verify mocks base method.
func (m *MockpasswordVerifier) Verify(passwordHash []byte, password domain.Password) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", passwordHash, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// Verify indicates an expected call of Verify.
func (mr *MockpasswordVerifierMockRecorder) Verify(passwordHash, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockpasswordVerifier)(nil).Verify), passwordHash, password)
}

// MocktokenBuilder is a mock of tokenBuilder interface.
type MocktokenBuilder struct {
	ctrl     *gomock.Controller
	recorder *MocktokenBuilderMockRecorder
	isgomock struct{}
}

// MocktokenBuilderMockRecorder is the mock recorder for MocktokenBuilder.
type MocktokenBuilderMockRecorder struct {
	mock *MocktokenBuilder
}

// NewMocktokenBuilder creates a new mock instance.
func NewMocktokenBuilder(ctrl *gomock.Controller) *MocktokenBuilder {
	mock := &MocktokenBuilder{ctrl: ctrl}
	mock.recorder = &MocktokenBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktokenBuilder) EXPECT() *MocktokenBuilderMockRecorder {
	return m.recorder
}

// Build mocks base method.
func (m *MocktokenBuilder) Build(userID int64, tokenExpiration time.Duration) (domain.UserCreateTokenOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Build", userID, tokenExpiration)
	ret0, _ := ret[0].(domain.UserCreateTokenOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Build indicates an expected call of Build.
func (mr *MocktokenBuilderMockRecorder) Build(userID, tokenExpiration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Build", reflect.TypeOf((*MocktokenBuilder)(nil).Build), userID, tokenExpiration)
}
