/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/project/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать проект */
        post: operations["projectCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project/delete/{projectID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить проект */
        delete: operations["projectDeleteByID"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project/get/{projectID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить проект по ID */
        get: operations["projectGetByID"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список проектов */
        get: operations["projectList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project/update/{projectID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Обновить проект */
        post: operations["projectUpdateByID"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать задачу генерации */
        post: operations["taskCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task/get/{taskID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить задачу генерации по ID */
        get: operations["taskGetByID"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список задач генерации */
        get: operations["taskList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/template/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать шаблон */
        post: operations["templateCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/template/delete/{templateID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить шаблон */
        delete: operations["templateDeleteByID"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/template/get/{templateID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить шаблон по ID */
        get: operations["templateGetByID"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/template/list/{projectID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список шаблонов в проекте */
        get: operations["templateList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/template/update/{templateID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Обновить шаблон */
        post: operations["templateUpdateByID"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать пользователя */
        post: operations["userCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить пользователя */
        get: operations["userGetByID"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/token/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать токен пользователя */
        post: operations["userTokenCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/token/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить токен пользователя (logout) */
        delete: operations["userTokenDelete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version/create_from": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать версию шаблона из другой версии */
        post: operations["versionCreateFrom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать версию шаблона */
        post: operations["versionCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version/list/{templateID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список шаблонов в проекте */
        get: operations["versionList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ProjectCreateRequest: {
            /** @description Название проекта */
            name: string;
        };
        /** @description Ошибка */
        Error: {
            message: string;
        };
        ProjectGetByIDResponse: {
            /** @description Название проекта */
            name: string;
            /** @description Имя автора проекта */
            authorName: string;
        };
        ProjectListResponse: {
            /** @description Список проектов */
            projects: {
                /**
                 * Format: int64
                 * @description ID проекта
                 */
                id: number;
                /** @description Название проекта */
                name: string;
                /** @description Имя автора проекта */
                authorName: string;
            }[];
            /**
             * Format: int64
             * @description Общее количество проектов
             */
            totalProjects: number;
            /**
             * Format: int64
             * @description Общее количество страниц
             */
            totalPages: number;
        };
        ProjectUpdateRequest: {
            /** @description Название проекта */
            name: string;
        };
        TaskCreateRequest: {
            /**
             * Format: int64
             * @description ID версии шаблона
             */
            versionID: number;
            /** @description Пэйлоад задачи */
            payload: {
                [key: string]: string;
            };
        };
        /**
         * @description Статус задачи
         * @enum {string}
         */
        TaskStatus: "created" | "in_progress" | "succeed" | "failed";
        TaskGetByIDResponse: {
            task: {
                /**
                 * Format: int64
                 * @description ID задачи
                 */
                id: number;
                /**
                 * Format: int64
                 * @description ID версии
                 */
                versionID: number;
                status: components["schemas"]["TaskStatus"];
                /** @description Пэйлоад задачи */
                payload: {
                    [key: string]: string;
                };
                /** @description Ошибка обработки задачи */
                error?: {
                    /** @description Сообщение ошибки */
                    message?: string;
                    variableErrors?: {
                        /**
                         * Format: int64
                         * @description ID переменной
                         */
                        id: number;
                        /** @description Название переменной */
                        name: string;
                        /** @description Сообщение ошибки */
                        message?: string;
                        constraintErrors?: {
                            /**
                             * Format: int64
                             * @description ID ограничения
                             */
                            id: number;
                            /** @description Название ограничения */
                            name: string;
                            /** @description Сообщение ошибки */
                            message?: string;
                        }[];
                    }[];
                };
                /** @description Имя создателя задачи */
                creatorName: string;
                /**
                 * Format: date-time
                 * @description Дата и время создания задачи
                 */
                createdAt: string;
                /**
                 * Format: date-time
                 * @description Дата и время обновления задачи
                 */
                updatedAt?: string;
            };
            /** Format: byte */
            result?: string;
        };
        TaskListResponse: {
            /** @description Список задач генерации */
            tasks: {
                /**
                 * Format: int64
                 * @description ID задачи генерации
                 */
                id: number;
                /**
                 * Format: int64
                 * @description Номер версии
                 */
                versionNumber: number;
                status: components["schemas"]["TaskStatus"];
                /** @description Имя создателя задачи */
                creatorName: string;
                /**
                 * Format: date-time
                 * @description Дата и время создания задачи
                 */
                createdAt: string;
                /**
                 * Format: date-time
                 * @description Дата и время обновления задачи
                 */
                updatedAt?: string;
            }[];
            /**
             * Format: int64
             * @description Общее количество задач
             */
            totalTasks: number;
            /**
             * Format: int64
             * @description Общее количество страниц
             */
            totalPages: number;
        };
        TemplateCreateRequest: {
            /** @description Название шаблона */
            name: string;
            /**
             * Format: int64
             * @description ID проекта
             */
            projectID: number;
        };
        TemplateGetByIDVersion: {
            /**
             * Format: int64
             * @description ID последней версии шаблона
             */
            id: number;
            /**
             * Format: int64
             * @description Номер последней версии шаблона
             */
            number: number;
            /**
             * Format: date-time
             * @description Дата и время создания версии
             */
            createdAt: string;
            /**
             * Format: byte
             * @description Данные шаблона
             */
            data: string;
            /** @description Список переменных шаблона */
            variables: {
                /**
                 * Format: int64
                 * @description ID переменной
                 */
                id: number;
                /** @description Название переменной */
                name: string;
                /**
                 * @description Тип переменной
                 * @enum {string}
                 */
                type: "string" | "integer" | "float";
                /** @description Выражение переменной */
                expression?: string;
                /** @description Являтеся ли переменная входной */
                isInput: boolean;
                /** @description Список ограничений переменной */
                constraints: {
                    /**
                     * Format: int64
                     * @description ID ограничения
                     */
                    id: number;
                    /** @description Название ограничения */
                    name: string;
                    /** @description Выражение ограничения */
                    expression: string;
                    /** @description Активно ли ограничение */
                    isActive: boolean;
                }[];
            }[];
        };
        TemplateGetByIDResponse: {
            /** @description Название шаблона */
            name: string;
            version?: components["schemas"]["TemplateGetByIDVersion"];
        };
        TemplateListResponse: {
            /** @description Список шаблонов */
            templates: {
                /**
                 * Format: int64
                 * @description ID шаблона
                 */
                id: number;
                /** @description Название шаблона */
                name: string;
                /** @description Имя автора шаблона */
                authorName: string;
                /**
                 * Format: date-time
                 * @description Дата и время создания шаблона
                 */
                createdAt: string;
                /**
                 * Format: date-time
                 * @description Дата и время обновления шаблона
                 */
                updatedAt?: string;
            }[];
            /**
             * Format: int64
             * @description Общее количество шаблонов
             */
            totalTemplates: number;
            /**
             * Format: int64
             * @description Общее количество страниц
             */
            totalPages: number;
        };
        TemplateUpdateRequest: {
            /** @description Название шаблона */
            name: string;
        };
        UserCreateRequest: {
            /** @description Имя пользователя */
            name: string;
            /**
             * Format: email
             * @description Электронный адрес пользователя
             */
            email: string;
            /**
             * Format: password
             * @description Пароль пользователя
             */
            password: string;
        };
        UserGetByIDResponse: {
            /**
             * Format: int64
             * @description ID пользователя
             */
            id: number;
            /** @description Имя пользователя */
            name: string;
            /** @description Электронный адрес пользователя */
            email: string;
            /**
             * Format: date-time
             * @description Дата и время создания пользователя
             */
            createdAt: string;
        };
        UserTokenCreateRequest: {
            /** @description Имя пользователя */
            name: string;
            /**
             * Format: password
             * @description Пароль пользователя
             */
            password: string;
            /** @description При true cookie сохраняется между сессиями браузера; при false выставляется session-cookie */
            remember: boolean;
        };
        VersionCreateFromRequest: {
            /**
             * Format: int64
             * @description ID шаблона
             */
            templateID: number;
            /**
             * Format: int64
             * @description ID версии
             */
            versionID: number;
        };
        VersionCreateRequest: {
            /**
             * Format: int64
             * @description ID шаблона
             */
            templateID: number;
            /**
             * Format: byte
             * @description Данные шаблона
             */
            data: string;
            /** @description Список переменных шаблона */
            variables: {
                /** @description Название переменной */
                name: string;
                /**
                 * @description Тип переменной
                 * @enum {string}
                 */
                type: "string" | "integer" | "float";
                /** @description Выражение переменной */
                expression?: string;
                /** @description Является ли переменная входной */
                isInput: boolean;
                /** @description Список ограничений переменной */
                constraints: {
                    /** @description Название ограничения */
                    name: string;
                    /** @description Выражение ограничения */
                    expression: string;
                    /** @description Активно ли ограничение */
                    isActive: boolean;
                }[];
            }[];
        };
        VersionCreateResponse: {
            /**
             * Format: int64
             * @description ID версии
             */
            id: number;
        };
        VersionListResponse: {
            /** @description Список версий */
            versions: {
                /**
                 * Format: int64
                 * @description ID версии
                 */
                id: number;
                /**
                 * Format: int64
                 * @description Номер версии
                 */
                number: number;
                /** @description Имя автора версии */
                authorName: string;
                /**
                 * Format: date-time
                 * @description Дата и время создания версии
                 */
                createdAt: string;
            }[];
        };
    };
    responses: never;
    parameters: {
        /** @description ID пользователя */
        UserID: number;
        /** @description ID проекта */
        ProjectID: number;
        /** @description Номер страницы */
        Page: number;
        /** @description Количество записей на странице */
        Size: number;
        /** @description Сортировка списка */
        Sorting: {
            /** @description Атрибут, по которому сортируется список */
            attribute: string;
            /**
             * @description Направление, по которому сортируется список
             * @enum {string}
             */
            direction: "ASC" | "DESC";
        };
        /** @description Название проекта */
        ProjectName: string;
        /** @description ID задачи */
        TaskID: number;
        /** @description ID шаблона */
        TaskTemplateID: number;
        /** @description ID создателя задачи */
        TaskCreatorID: number;
        /** @description ID шаблона */
        TemplateID: number;
        /** @description Название шаблона */
        TemplateName: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    projectCreate: {
        parameters: {
            query?: never;
            header: {
                /** @description ID пользователя */
                "X-User-Id": components["parameters"]["UserID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    projectDeleteByID: {
        parameters: {
            query?: never;
            header: {
                /** @description ID пользователя */
                "X-User-Id": components["parameters"]["UserID"];
            };
            path: {
                /** @description ID проекта */
                projectID: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    projectGetByID: {
        parameters: {
            query?: never;
            header: {
                /** @description ID пользователя */
                "X-User-Id": components["parameters"]["UserID"];
            };
            path: {
                /** @description ID проекта */
                projectID: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectGetByIDResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    projectList: {
        parameters: {
            query: {
                /** @description Номер страницы */
                page: components["parameters"]["Page"];
                /** @description Количество записей на странице */
                size: components["parameters"]["Size"];
                /** @description Сортировка списка */
                sorting?: components["parameters"]["Sorting"];
                /** @description Название проекта */
                projectName?: components["parameters"]["ProjectName"];
            };
            header: {
                /** @description ID пользователя */
                "X-User-Id": components["parameters"]["UserID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    projectUpdateByID: {
        parameters: {
            query?: never;
            header: {
                /** @description ID пользователя */
                "X-User-Id": components["parameters"]["UserID"];
            };
            path: {
                /** @description ID проекта */
                projectID: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdateRequest"];
            };
        };
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    taskCreate: {
        parameters: {
            query?: never;
            header: {
                /** @description ID пользователя */
                "X-User-Id": components["parameters"]["UserID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    taskGetByID: {
        parameters: {
            query?: never;
            header: {
                /** @description ID пользователя */
                "X-User-Id": components["parameters"]["UserID"];
            };
            path: {
                /** @description ID задачи */
                taskID: components["parameters"]["TaskID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskGetByIDResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    taskList: {
        parameters: {
            query: {
                /** @description Номер страницы */
                page: components["parameters"]["Page"];
                /** @description Количество записей на странице */
                size: components["parameters"]["Size"];
                /** @description Сортировка списка */
                sorting?: components["parameters"]["Sorting"];
                /** @description ID шаблона */
                templateID: components["parameters"]["TaskTemplateID"];
                /** @description ID создателя задачи */
                creatorID?: components["parameters"]["TaskCreatorID"];
            };
            header: {
                /** @description ID пользователя */
                "X-User-Id": components["parameters"]["UserID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskListResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    templateCreate: {
        parameters: {
            query?: never;
            header: {
                /** @description ID пользователя */
                "X-User-Id": components["parameters"]["UserID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    templateDeleteByID: {
        parameters: {
            query?: never;
            header: {
                /** @description ID пользователя */
                "X-User-Id": components["parameters"]["UserID"];
            };
            path: {
                /** @description ID шаблона */
                templateID: components["parameters"]["TemplateID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    templateGetByID: {
        parameters: {
            query?: never;
            header: {
                /** @description ID пользователя */
                "X-User-Id": components["parameters"]["UserID"];
            };
            path: {
                /** @description ID шаблона */
                templateID: components["parameters"]["TemplateID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateGetByIDResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    templateList: {
        parameters: {
            query: {
                /** @description Номер страницы */
                page: components["parameters"]["Page"];
                /** @description Количество записей на странице */
                size: components["parameters"]["Size"];
                /** @description Сортировка списка */
                sorting?: components["parameters"]["Sorting"];
                /** @description Название шаблона */
                templateName?: components["parameters"]["TemplateName"];
            };
            header: {
                /** @description ID пользователя */
                "X-User-Id": components["parameters"]["UserID"];
            };
            path: {
                /** @description ID проекта */
                projectID: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateListResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    templateUpdateByID: {
        parameters: {
            query?: never;
            header: {
                /** @description ID пользователя */
                "X-User-Id": components["parameters"]["UserID"];
            };
            path: {
                /** @description ID шаблона */
                templateID: components["parameters"]["TemplateID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateUpdateRequest"];
            };
        };
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    userCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    userGetByID: {
        parameters: {
            query?: never;
            header: {
                /** @description ID пользователя */
                "X-User-Id": components["parameters"]["UserID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserGetByIDResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    userTokenCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserTokenCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    "Set-Cookie": string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    userTokenDelete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    "Set-Cookie": string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    versionCreateFrom: {
        parameters: {
            query?: never;
            header: {
                /** @description ID пользователя */
                "X-User-Id": components["parameters"]["UserID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionCreateFromRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    versionCreate: {
        parameters: {
            query?: never;
            header: {
                /** @description ID пользователя */
                "X-User-Id": components["parameters"]["UserID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionCreateResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    versionList: {
        parameters: {
            query?: never;
            header: {
                /** @description ID пользователя */
                "X-User-Id": components["parameters"]["UserID"];
            };
            path: {
                /** @description ID шаблона */
                templateID: components["parameters"]["TemplateID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionListResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
