// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -package usecase -source contract.go -destination contract_mock.go
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	domain "github.com/qsoulior/tech-generator/backend/internal/usecase/template_get_by_id/domain"
	gomock "go.uber.org/mock/gomock"
)

// MocktemplateRepository is a mock of templateRepository interface.
type MocktemplateRepository struct {
	ctrl     *gomock.Controller
	recorder *MocktemplateRepositoryMockRecorder
	isgomock struct{}
}

// MocktemplateRepositoryMockRecorder is the mock recorder for MocktemplateRepository.
type MocktemplateRepositoryMockRecorder struct {
	mock *MocktemplateRepository
}

// NewMocktemplateRepository creates a new mock instance.
func NewMocktemplateRepository(ctrl *gomock.Controller) *MocktemplateRepository {
	mock := &MocktemplateRepository{ctrl: ctrl}
	mock.recorder = &MocktemplateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktemplateRepository) EXPECT() *MocktemplateRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MocktemplateRepository) GetByID(ctx context.Context, id int64) (*domain.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MocktemplateRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MocktemplateRepository)(nil).GetByID), ctx, id)
}

// MocktemplateVersionRepository is a mock of templateVersionRepository interface.
type MocktemplateVersionRepository struct {
	ctrl     *gomock.Controller
	recorder *MocktemplateVersionRepositoryMockRecorder
	isgomock struct{}
}

// MocktemplateVersionRepositoryMockRecorder is the mock recorder for MocktemplateVersionRepository.
type MocktemplateVersionRepositoryMockRecorder struct {
	mock *MocktemplateVersionRepository
}

// NewMocktemplateVersionRepository creates a new mock instance.
func NewMocktemplateVersionRepository(ctrl *gomock.Controller) *MocktemplateVersionRepository {
	mock := &MocktemplateVersionRepository{ctrl: ctrl}
	mock.recorder = &MocktemplateVersionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktemplateVersionRepository) EXPECT() *MocktemplateVersionRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MocktemplateVersionRepository) GetByID(ctx context.Context, id int64) (*domain.TemplateVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.TemplateVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MocktemplateVersionRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MocktemplateVersionRepository)(nil).GetByID), ctx, id)
}

// MockvariableRepository is a mock of variableRepository interface.
type MockvariableRepository struct {
	ctrl     *gomock.Controller
	recorder *MockvariableRepositoryMockRecorder
	isgomock struct{}
}

// MockvariableRepositoryMockRecorder is the mock recorder for MockvariableRepository.
type MockvariableRepositoryMockRecorder struct {
	mock *MockvariableRepository
}

// NewMockvariableRepository creates a new mock instance.
func NewMockvariableRepository(ctrl *gomock.Controller) *MockvariableRepository {
	mock := &MockvariableRepository{ctrl: ctrl}
	mock.recorder = &MockvariableRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockvariableRepository) EXPECT() *MockvariableRepositoryMockRecorder {
	return m.recorder
}

// ListByVersionID mocks base method.
func (m *MockvariableRepository) ListByVersionID(ctx context.Context, versionID int64) ([]domain.Variable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByVersionID", ctx, versionID)
	ret0, _ := ret[0].([]domain.Variable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByVersionID indicates an expected call of ListByVersionID.
func (mr *MockvariableRepositoryMockRecorder) ListByVersionID(ctx, versionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByVersionID", reflect.TypeOf((*MockvariableRepository)(nil).ListByVersionID), ctx, versionID)
}

// MockvariableConstraintRepository is a mock of variableConstraintRepository interface.
type MockvariableConstraintRepository struct {
	ctrl     *gomock.Controller
	recorder *MockvariableConstraintRepositoryMockRecorder
	isgomock struct{}
}

// MockvariableConstraintRepositoryMockRecorder is the mock recorder for MockvariableConstraintRepository.
type MockvariableConstraintRepositoryMockRecorder struct {
	mock *MockvariableConstraintRepository
}

// NewMockvariableConstraintRepository creates a new mock instance.
func NewMockvariableConstraintRepository(ctrl *gomock.Controller) *MockvariableConstraintRepository {
	mock := &MockvariableConstraintRepository{ctrl: ctrl}
	mock.recorder = &MockvariableConstraintRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockvariableConstraintRepository) EXPECT() *MockvariableConstraintRepositoryMockRecorder {
	return m.recorder
}

// ListByVariableIDs mocks base method.
func (m *MockvariableConstraintRepository) ListByVariableIDs(ctx context.Context, variableIDs []int64) ([]domain.VariableConstraint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByVariableIDs", ctx, variableIDs)
	ret0, _ := ret[0].([]domain.VariableConstraint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByVariableIDs indicates an expected call of ListByVariableIDs.
func (mr *MockvariableConstraintRepositoryMockRecorder) ListByVariableIDs(ctx, variableIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByVariableIDs", reflect.TypeOf((*MockvariableConstraintRepository)(nil).ListByVariableIDs), ctx, variableIDs)
}
