// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -package usecase -source contract.go -destination contract_mock.go
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	domain "github.com/qsoulior/tech-generator/backend/internal/usecase/task_list/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockversionRepository is a mock of versionRepository interface.
type MockversionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockversionRepositoryMockRecorder
	isgomock struct{}
}

// MockversionRepositoryMockRecorder is the mock recorder for MockversionRepository.
type MockversionRepositoryMockRecorder struct {
	mock *MockversionRepository
}

// NewMockversionRepository creates a new mock instance.
func NewMockversionRepository(ctrl *gomock.Controller) *MockversionRepository {
	mock := &MockversionRepository{ctrl: ctrl}
	mock.recorder = &MockversionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockversionRepository) EXPECT() *MockversionRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockversionRepository) GetByID(ctx context.Context, id int64) (*domain.Version, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Version)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockversionRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockversionRepository)(nil).GetByID), ctx, id)
}

// MocktaskRepository is a mock of taskRepository interface.
type MocktaskRepository struct {
	ctrl     *gomock.Controller
	recorder *MocktaskRepositoryMockRecorder
	isgomock struct{}
}

// MocktaskRepositoryMockRecorder is the mock recorder for MocktaskRepository.
type MocktaskRepositoryMockRecorder struct {
	mock *MocktaskRepository
}

// NewMocktaskRepository creates a new mock instance.
func NewMocktaskRepository(ctrl *gomock.Controller) *MocktaskRepository {
	mock := &MocktaskRepository{ctrl: ctrl}
	mock.recorder = &MocktaskRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktaskRepository) EXPECT() *MocktaskRepositoryMockRecorder {
	return m.recorder
}

// GetTotal mocks base method.
func (m *MocktaskRepository) GetTotal(ctx context.Context, in domain.TaskListIn) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotal", ctx, in)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotal indicates an expected call of GetTotal.
func (mr *MocktaskRepositoryMockRecorder) GetTotal(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotal", reflect.TypeOf((*MocktaskRepository)(nil).GetTotal), ctx, in)
}

// List mocks base method.
func (m *MocktaskRepository) List(ctx context.Context, in domain.TaskListIn) ([]domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, in)
	ret0, _ := ret[0].([]domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MocktaskRepositoryMockRecorder) List(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MocktaskRepository)(nil).List), ctx, in)
}
