// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -package usecase -source contract.go -destination contract_mock.go
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	domain "github.com/qsoulior/tech-generator/backend/internal/service/version_create/domain"
	domain0 "github.com/qsoulior/tech-generator/backend/internal/service/version_get/domain"
	domain1 "github.com/qsoulior/tech-generator/backend/internal/usecase/template_create_from_default/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockprojectRepository is a mock of projectRepository interface.
type MockprojectRepository struct {
	ctrl     *gomock.Controller
	recorder *MockprojectRepositoryMockRecorder
	isgomock struct{}
}

// MockprojectRepositoryMockRecorder is the mock recorder for MockprojectRepository.
type MockprojectRepositoryMockRecorder struct {
	mock *MockprojectRepository
}

// NewMockprojectRepository creates a new mock instance.
func NewMockprojectRepository(ctrl *gomock.Controller) *MockprojectRepository {
	mock := &MockprojectRepository{ctrl: ctrl}
	mock.recorder = &MockprojectRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockprojectRepository) EXPECT() *MockprojectRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockprojectRepository) GetByID(ctx context.Context, id int64) (*domain1.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain1.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockprojectRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockprojectRepository)(nil).GetByID), ctx, id)
}

// MocksourceTemplateRepository is a mock of sourceTemplateRepository interface.
type MocksourceTemplateRepository struct {
	ctrl     *gomock.Controller
	recorder *MocksourceTemplateRepositoryMockRecorder
	isgomock struct{}
}

// MocksourceTemplateRepositoryMockRecorder is the mock recorder for MocksourceTemplateRepository.
type MocksourceTemplateRepositoryMockRecorder struct {
	mock *MocksourceTemplateRepository
}

// NewMocksourceTemplateRepository creates a new mock instance.
func NewMocksourceTemplateRepository(ctrl *gomock.Controller) *MocksourceTemplateRepository {
	mock := &MocksourceTemplateRepository{ctrl: ctrl}
	mock.recorder = &MocksourceTemplateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksourceTemplateRepository) EXPECT() *MocksourceTemplateRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MocksourceTemplateRepository) GetByID(ctx context.Context, id int64) (*domain1.SourceTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain1.SourceTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MocksourceTemplateRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MocksourceTemplateRepository)(nil).GetByID), ctx, id)
}

// MocknewTemplateRepository is a mock of newTemplateRepository interface.
type MocknewTemplateRepository struct {
	ctrl     *gomock.Controller
	recorder *MocknewTemplateRepositoryMockRecorder
	isgomock struct{}
}

// MocknewTemplateRepositoryMockRecorder is the mock recorder for MocknewTemplateRepository.
type MocknewTemplateRepositoryMockRecorder struct {
	mock *MocknewTemplateRepository
}

// NewMocknewTemplateRepository creates a new mock instance.
func NewMocknewTemplateRepository(ctrl *gomock.Controller) *MocknewTemplateRepository {
	mock := &MocknewTemplateRepository{ctrl: ctrl}
	mock.recorder = &MocknewTemplateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknewTemplateRepository) EXPECT() *MocknewTemplateRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MocknewTemplateRepository) Create(ctx context.Context, template domain1.Template) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, template)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MocknewTemplateRepositoryMockRecorder) Create(ctx, template any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MocknewTemplateRepository)(nil).Create), ctx, template)
}

// MockversionGetService is a mock of versionGetService interface.
type MockversionGetService struct {
	ctrl     *gomock.Controller
	recorder *MockversionGetServiceMockRecorder
	isgomock struct{}
}

// MockversionGetServiceMockRecorder is the mock recorder for MockversionGetService.
type MockversionGetServiceMockRecorder struct {
	mock *MockversionGetService
}

// NewMockversionGetService creates a new mock instance.
func NewMockversionGetService(ctrl *gomock.Controller) *MockversionGetService {
	mock := &MockversionGetService{ctrl: ctrl}
	mock.recorder = &MockversionGetServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockversionGetService) EXPECT() *MockversionGetServiceMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockversionGetService) Handle(ctx context.Context, versionID int64) (*domain0.Version, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, versionID)
	ret0, _ := ret[0].(*domain0.Version)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockversionGetServiceMockRecorder) Handle(ctx, versionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockversionGetService)(nil).Handle), ctx, versionID)
}

// MockversionCreateService is a mock of versionCreateService interface.
type MockversionCreateService struct {
	ctrl     *gomock.Controller
	recorder *MockversionCreateServiceMockRecorder
	isgomock struct{}
}

// MockversionCreateServiceMockRecorder is the mock recorder for MockversionCreateService.
type MockversionCreateServiceMockRecorder struct {
	mock *MockversionCreateService
}

// NewMockversionCreateService creates a new mock instance.
func NewMockversionCreateService(ctrl *gomock.Controller) *MockversionCreateService {
	mock := &MockversionCreateService{ctrl: ctrl}
	mock.recorder = &MockversionCreateServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockversionCreateService) EXPECT() *MockversionCreateServiceMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockversionCreateService) Handle(ctx context.Context, in domain.VersionCreateIn) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, in)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockversionCreateServiceMockRecorder) Handle(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockversionCreateService)(nil).Handle), ctx, in)
}
