// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -package usecase -source contract.go -destination contract_mock.go
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	domain "github.com/qsoulior/tech-generator/backend/internal/usecase/project_list_by_user/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockprojectRepository is a mock of projectRepository interface.
type MockprojectRepository struct {
	ctrl     *gomock.Controller
	recorder *MockprojectRepositoryMockRecorder
	isgomock struct{}
}

// MockprojectRepositoryMockRecorder is the mock recorder for MockprojectRepository.
type MockprojectRepositoryMockRecorder struct {
	mock *MockprojectRepository
}

// NewMockprojectRepository creates a new mock instance.
func NewMockprojectRepository(ctrl *gomock.Controller) *MockprojectRepository {
	mock := &MockprojectRepository{ctrl: ctrl}
	mock.recorder = &MockprojectRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockprojectRepository) EXPECT() *MockprojectRepositoryMockRecorder {
	return m.recorder
}

// ListByAuthorID mocks base method.
func (m *MockprojectRepository) ListByAuthorID(ctx context.Context, in domain.ProjectListByUserIn) ([]domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAuthorID", ctx, in)
	ret0, _ := ret[0].([]domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAuthorID indicates an expected call of ListByAuthorID.
func (mr *MockprojectRepositoryMockRecorder) ListByAuthorID(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAuthorID", reflect.TypeOf((*MockprojectRepository)(nil).ListByAuthorID), ctx, in)
}

// ListByProjectUserID mocks base method.
func (m *MockprojectRepository) ListByProjectUserID(ctx context.Context, in domain.ProjectListByUserIn) ([]domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByProjectUserID", ctx, in)
	ret0, _ := ret[0].([]domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByProjectUserID indicates an expected call of ListByProjectUserID.
func (mr *MockprojectRepositoryMockRecorder) ListByProjectUserID(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByProjectUserID", reflect.TypeOf((*MockprojectRepository)(nil).ListByProjectUserID), ctx, in)
}
