// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -package usecase -source contract.go -destination contract_mock.go
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	domain "github.com/qsoulior/tech-generator/backend/internal/usecase/project_list_by_user/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockprojectRepository is a mock of projectRepository interface.
type MockprojectRepository struct {
	ctrl     *gomock.Controller
	recorder *MockprojectRepositoryMockRecorder
	isgomock struct{}
}

// MockprojectRepositoryMockRecorder is the mock recorder for MockprojectRepository.
type MockprojectRepositoryMockRecorder struct {
	mock *MockprojectRepository
}

// NewMockprojectRepository creates a new mock instance.
func NewMockprojectRepository(ctrl *gomock.Controller) *MockprojectRepository {
	mock := &MockprojectRepository{ctrl: ctrl}
	mock.recorder = &MockprojectRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockprojectRepository) EXPECT() *MockprojectRepositoryMockRecorder {
	return m.recorder
}

// GetTotalByUserID mocks base method.
func (m *MockprojectRepository) GetTotalByUserID(ctx context.Context, in domain.ProjectListByUserIn) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalByUserID", ctx, in)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalByUserID indicates an expected call of GetTotalByUserID.
func (mr *MockprojectRepositoryMockRecorder) GetTotalByUserID(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalByUserID", reflect.TypeOf((*MockprojectRepository)(nil).GetTotalByUserID), ctx, in)
}

// ListByUserID mocks base method.
func (m *MockprojectRepository) ListByUserID(ctx context.Context, in domain.ProjectListByUserIn) ([]domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", ctx, in)
	ret0, _ := ret[0].([]domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockprojectRepositoryMockRecorder) ListByUserID(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockprojectRepository)(nil).ListByUserID), ctx, in)
}
