// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -package usecase -source contract.go -destination contract_mock.go
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	domain "github.com/qsoulior/tech-generator/backend/internal/usecase/template_version_create/domain"
	gomock "go.uber.org/mock/gomock"
)

// MocktemplateRepository is a mock of templateRepository interface.
type MocktemplateRepository struct {
	ctrl     *gomock.Controller
	recorder *MocktemplateRepositoryMockRecorder
	isgomock struct{}
}

// MocktemplateRepositoryMockRecorder is the mock recorder for MocktemplateRepository.
type MocktemplateRepositoryMockRecorder struct {
	mock *MocktemplateRepository
}

// NewMocktemplateRepository creates a new mock instance.
func NewMocktemplateRepository(ctrl *gomock.Controller) *MocktemplateRepository {
	mock := &MocktemplateRepository{ctrl: ctrl}
	mock.recorder = &MocktemplateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktemplateRepository) EXPECT() *MocktemplateRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MocktemplateRepository) GetByID(ctx context.Context, id int64) (*domain.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MocktemplateRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MocktemplateRepository)(nil).GetByID), ctx, id)
}

// UpdateByID mocks base method.
func (m *MocktemplateRepository) UpdateByID(ctx context.Context, template domain.TemplateToUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", ctx, template)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MocktemplateRepositoryMockRecorder) UpdateByID(ctx, template any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MocktemplateRepository)(nil).UpdateByID), ctx, template)
}

// MocktemplateVersionRepository is a mock of templateVersionRepository interface.
type MocktemplateVersionRepository struct {
	ctrl     *gomock.Controller
	recorder *MocktemplateVersionRepositoryMockRecorder
	isgomock struct{}
}

// MocktemplateVersionRepositoryMockRecorder is the mock recorder for MocktemplateVersionRepository.
type MocktemplateVersionRepositoryMockRecorder struct {
	mock *MocktemplateVersionRepository
}

// NewMocktemplateVersionRepository creates a new mock instance.
func NewMocktemplateVersionRepository(ctrl *gomock.Controller) *MocktemplateVersionRepository {
	mock := &MocktemplateVersionRepository{ctrl: ctrl}
	mock.recorder = &MocktemplateVersionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktemplateVersionRepository) EXPECT() *MocktemplateVersionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MocktemplateVersionRepository) Create(ctx context.Context, templateVersion domain.TemplateVersion) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, templateVersion)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MocktemplateVersionRepositoryMockRecorder) Create(ctx, templateVersion any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MocktemplateVersionRepository)(nil).Create), ctx, templateVersion)
}

// MockvariableRepository is a mock of variableRepository interface.
type MockvariableRepository struct {
	ctrl     *gomock.Controller
	recorder *MockvariableRepositoryMockRecorder
	isgomock struct{}
}

// MockvariableRepositoryMockRecorder is the mock recorder for MockvariableRepository.
type MockvariableRepositoryMockRecorder struct {
	mock *MockvariableRepository
}

// NewMockvariableRepository creates a new mock instance.
func NewMockvariableRepository(ctrl *gomock.Controller) *MockvariableRepository {
	mock := &MockvariableRepository{ctrl: ctrl}
	mock.recorder = &MockvariableRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockvariableRepository) EXPECT() *MockvariableRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockvariableRepository) Create(ctx context.Context, variables []domain.VariableToCreate) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, variables)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockvariableRepositoryMockRecorder) Create(ctx, variables any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockvariableRepository)(nil).Create), ctx, variables)
}

// MockvariableConstraintRepository is a mock of variableConstraintRepository interface.
type MockvariableConstraintRepository struct {
	ctrl     *gomock.Controller
	recorder *MockvariableConstraintRepositoryMockRecorder
	isgomock struct{}
}

// MockvariableConstraintRepositoryMockRecorder is the mock recorder for MockvariableConstraintRepository.
type MockvariableConstraintRepositoryMockRecorder struct {
	mock *MockvariableConstraintRepository
}

// NewMockvariableConstraintRepository creates a new mock instance.
func NewMockvariableConstraintRepository(ctrl *gomock.Controller) *MockvariableConstraintRepository {
	mock := &MockvariableConstraintRepository{ctrl: ctrl}
	mock.recorder = &MockvariableConstraintRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockvariableConstraintRepository) EXPECT() *MockvariableConstraintRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockvariableConstraintRepository) Create(ctx context.Context, constraints []domain.VariableConstraintToCreate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, constraints)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockvariableConstraintRepositoryMockRecorder) Create(ctx, constraints any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockvariableConstraintRepository)(nil).Create), ctx, constraints)
}
