// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -package usecase -source contract.go -destination contract_mock.go
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	domain "github.com/qsoulior/tech-generator/backend/internal/usecase/project_create/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockprojectRepository is a mock of projectRepository interface.
type MockprojectRepository struct {
	ctrl     *gomock.Controller
	recorder *MockprojectRepositoryMockRecorder
	isgomock struct{}
}

// MockprojectRepositoryMockRecorder is the mock recorder for MockprojectRepository.
type MockprojectRepositoryMockRecorder struct {
	mock *MockprojectRepository
}

// NewMockprojectRepository creates a new mock instance.
func NewMockprojectRepository(ctrl *gomock.Controller) *MockprojectRepository {
	mock := &MockprojectRepository{ctrl: ctrl}
	mock.recorder = &MockprojectRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockprojectRepository) EXPECT() *MockprojectRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockprojectRepository) Create(ctx context.Context, project domain.Project) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, project)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockprojectRepositoryMockRecorder) Create(ctx, project any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockprojectRepository)(nil).Create), ctx, project)
}
