// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -package usecase -source contract.go -destination contract_mock.go
//

// Package usecase is a generated GoMock package.
package usecase

import (
	reflect "reflect"

	domain "github.com/qsoulior/tech-generator/backend/internal/usecase/user_token_parse/domain"
	gomock "go.uber.org/mock/gomock"
)

// MocktokenParser is a mock of tokenParser interface.
type MocktokenParser struct {
	ctrl     *gomock.Controller
	recorder *MocktokenParserMockRecorder
	isgomock struct{}
}

// MocktokenParserMockRecorder is the mock recorder for MocktokenParser.
type MocktokenParserMockRecorder struct {
	mock *MocktokenParser
}

// NewMocktokenParser creates a new mock instance.
func NewMocktokenParser(ctrl *gomock.Controller) *MocktokenParser {
	mock := &MocktokenParser{ctrl: ctrl}
	mock.recorder = &MocktokenParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktokenParser) EXPECT() *MocktokenParserMockRecorder {
	return m.recorder
}

// Parse mocks base method.
func (m *MocktokenParser) Parse(tokenString string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parse", tokenString)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Parse indicates an expected call of Parse.
func (mr *MocktokenParserMockRecorder) Parse(tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MocktokenParser)(nil).Parse), tokenString)
}
