// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -package usecase -source contract.go -destination contract_mock.go
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	domain "github.com/qsoulior/tech-generator/backend/internal/usecase/template_user_update/domain"
	gomock "go.uber.org/mock/gomock"
)

// MocktemplateRepository is a mock of templateRepository interface.
type MocktemplateRepository struct {
	ctrl     *gomock.Controller
	recorder *MocktemplateRepositoryMockRecorder
	isgomock struct{}
}

// MocktemplateRepositoryMockRecorder is the mock recorder for MocktemplateRepository.
type MocktemplateRepositoryMockRecorder struct {
	mock *MocktemplateRepository
}

// NewMocktemplateRepository creates a new mock instance.
func NewMocktemplateRepository(ctrl *gomock.Controller) *MocktemplateRepository {
	mock := &MocktemplateRepository{ctrl: ctrl}
	mock.recorder = &MocktemplateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktemplateRepository) EXPECT() *MocktemplateRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MocktemplateRepository) GetByID(ctx context.Context, id int64) (*domain.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MocktemplateRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MocktemplateRepository)(nil).GetByID), ctx, id)
}

// MocktemplateUserRepository is a mock of templateUserRepository interface.
type MocktemplateUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MocktemplateUserRepositoryMockRecorder
	isgomock struct{}
}

// MocktemplateUserRepositoryMockRecorder is the mock recorder for MocktemplateUserRepository.
type MocktemplateUserRepositoryMockRecorder struct {
	mock *MocktemplateUserRepository
}

// NewMocktemplateUserRepository creates a new mock instance.
func NewMocktemplateUserRepository(ctrl *gomock.Controller) *MocktemplateUserRepository {
	mock := &MocktemplateUserRepository{ctrl: ctrl}
	mock.recorder = &MocktemplateUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktemplateUserRepository) EXPECT() *MocktemplateUserRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MocktemplateUserRepository) Delete(ctx context.Context, templateID int64, userIDs []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, templateID, userIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MocktemplateUserRepositoryMockRecorder) Delete(ctx, templateID, userIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MocktemplateUserRepository)(nil).Delete), ctx, templateID, userIDs)
}

// GetByTemplateID mocks base method.
func (m *MocktemplateUserRepository) GetByTemplateID(ctx context.Context, templateID int64) ([]domain.TemplateUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTemplateID", ctx, templateID)
	ret0, _ := ret[0].([]domain.TemplateUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTemplateID indicates an expected call of GetByTemplateID.
func (mr *MocktemplateUserRepositoryMockRecorder) GetByTemplateID(ctx, templateID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTemplateID", reflect.TypeOf((*MocktemplateUserRepository)(nil).GetByTemplateID), ctx, templateID)
}

// Upsert mocks base method.
func (m *MocktemplateUserRepository) Upsert(ctx context.Context, templateID int64, users []domain.TemplateUser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, templateID, users)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MocktemplateUserRepositoryMockRecorder) Upsert(ctx, templateID, users any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MocktemplateUserRepository)(nil).Upsert), ctx, templateID, users)
}

// MockuserRepository is a mock of userRepository interface.
type MockuserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockuserRepositoryMockRecorder
	isgomock struct{}
}

// MockuserRepositoryMockRecorder is the mock recorder for MockuserRepository.
type MockuserRepositoryMockRecorder struct {
	mock *MockuserRepository
}

// NewMockuserRepository creates a new mock instance.
func NewMockuserRepository(ctrl *gomock.Controller) *MockuserRepository {
	mock := &MockuserRepository{ctrl: ctrl}
	mock.recorder = &MockuserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserRepository) EXPECT() *MockuserRepositoryMockRecorder {
	return m.recorder
}

// GetByIDs mocks base method.
func (m *MockuserRepository) GetByIDs(ctx context.Context, ids []int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDs", ctx, ids)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDs indicates an expected call of GetByIDs.
func (mr *MockuserRepositoryMockRecorder) GetByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDs", reflect.TypeOf((*MockuserRepository)(nil).GetByIDs), ctx, ids)
}
