// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -package usecase -source contract.go -destination contract_mock.go
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	domain "github.com/qsoulior/tech-generator/backend/internal/usecase/folder_create/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockfolderRepository is a mock of folderRepository interface.
type MockfolderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockfolderRepositoryMockRecorder
	isgomock struct{}
}

// MockfolderRepositoryMockRecorder is the mock recorder for MockfolderRepository.
type MockfolderRepositoryMockRecorder struct {
	mock *MockfolderRepository
}

// NewMockfolderRepository creates a new mock instance.
func NewMockfolderRepository(ctrl *gomock.Controller) *MockfolderRepository {
	mock := &MockfolderRepository{ctrl: ctrl}
	mock.recorder = &MockfolderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfolderRepository) EXPECT() *MockfolderRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockfolderRepository) Create(ctx context.Context, parentID int64, name string, authorID, rootAuthorID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, parentID, name, authorID, rootAuthorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockfolderRepositoryMockRecorder) Create(ctx, parentID, name, authorID, rootAuthorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockfolderRepository)(nil).Create), ctx, parentID, name, authorID, rootAuthorID)
}

// GetByID mocks base method.
func (m *MockfolderRepository) GetByID(ctx context.Context, id int64) (*domain.Folder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Folder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockfolderRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockfolderRepository)(nil).GetByID), ctx, id)
}
