// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -package publisher -source contract.go -destination contract_mock.go
//

// Package publisher is a generated GoMock package.
package publisher

import (
	context "context"
	reflect "reflect"

	amqp091 "github.com/rabbitmq/amqp091-go"
	gomock "go.uber.org/mock/gomock"
)

// MockamqpPublisher is a mock of amqpPublisher interface.
type MockamqpPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockamqpPublisherMockRecorder
	isgomock struct{}
}

// MockamqpPublisherMockRecorder is the mock recorder for MockamqpPublisher.
type MockamqpPublisherMockRecorder struct {
	mock *MockamqpPublisher
}

// NewMockamqpPublisher creates a new mock instance.
func NewMockamqpPublisher(ctrl *gomock.Controller) *MockamqpPublisher {
	mock := &MockamqpPublisher{ctrl: ctrl}
	mock.recorder = &MockamqpPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockamqpPublisher) EXPECT() *MockamqpPublisherMockRecorder {
	return m.recorder
}

// PublishWithContext mocks base method.
func (m *MockamqpPublisher) PublishWithContext(ctx context.Context, exchange, key string, mandatory, immediate bool, msg amqp091.Publishing) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishWithContext", ctx, exchange, key, mandatory, immediate, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishWithContext indicates an expected call of PublishWithContext.
func (mr *MockamqpPublisherMockRecorder) PublishWithContext(ctx, exchange, key, mandatory, immediate, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishWithContext", reflect.TypeOf((*MockamqpPublisher)(nil).PublishWithContext), ctx, exchange, key, mandatory, immediate, msg)
}
