// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -package service -source contract.go -destination contract_mock.go
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	domain "github.com/qsoulior/tech-generator/backend/internal/service/version_get/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockversionRepository is a mock of versionRepository interface.
type MockversionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockversionRepositoryMockRecorder
	isgomock struct{}
}

// MockversionRepositoryMockRecorder is the mock recorder for MockversionRepository.
type MockversionRepositoryMockRecorder struct {
	mock *MockversionRepository
}

// NewMockversionRepository creates a new mock instance.
func NewMockversionRepository(ctrl *gomock.Controller) *MockversionRepository {
	mock := &MockversionRepository{ctrl: ctrl}
	mock.recorder = &MockversionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockversionRepository) EXPECT() *MockversionRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockversionRepository) GetByID(ctx context.Context, id int64) (*domain.Version, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Version)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockversionRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockversionRepository)(nil).GetByID), ctx, id)
}

// MockvariableRepository is a mock of variableRepository interface.
type MockvariableRepository struct {
	ctrl     *gomock.Controller
	recorder *MockvariableRepositoryMockRecorder
	isgomock struct{}
}

// MockvariableRepositoryMockRecorder is the mock recorder for MockvariableRepository.
type MockvariableRepositoryMockRecorder struct {
	mock *MockvariableRepository
}

// NewMockvariableRepository creates a new mock instance.
func NewMockvariableRepository(ctrl *gomock.Controller) *MockvariableRepository {
	mock := &MockvariableRepository{ctrl: ctrl}
	mock.recorder = &MockvariableRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockvariableRepository) EXPECT() *MockvariableRepositoryMockRecorder {
	return m.recorder
}

// ListByVersionID mocks base method.
func (m *MockvariableRepository) ListByVersionID(ctx context.Context, versionID int64) ([]domain.Variable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByVersionID", ctx, versionID)
	ret0, _ := ret[0].([]domain.Variable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByVersionID indicates an expected call of ListByVersionID.
func (mr *MockvariableRepositoryMockRecorder) ListByVersionID(ctx, versionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByVersionID", reflect.TypeOf((*MockvariableRepository)(nil).ListByVersionID), ctx, versionID)
}

// MockconstraintRepository is a mock of constraintRepository interface.
type MockconstraintRepository struct {
	ctrl     *gomock.Controller
	recorder *MockconstraintRepositoryMockRecorder
	isgomock struct{}
}

// MockconstraintRepositoryMockRecorder is the mock recorder for MockconstraintRepository.
type MockconstraintRepositoryMockRecorder struct {
	mock *MockconstraintRepository
}

// NewMockconstraintRepository creates a new mock instance.
func NewMockconstraintRepository(ctrl *gomock.Controller) *MockconstraintRepository {
	mock := &MockconstraintRepository{ctrl: ctrl}
	mock.recorder = &MockconstraintRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockconstraintRepository) EXPECT() *MockconstraintRepositoryMockRecorder {
	return m.recorder
}

// ListByVariableIDs mocks base method.
func (m *MockconstraintRepository) ListByVariableIDs(ctx context.Context, variableIDs []int64) ([]domain.Constraint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByVariableIDs", ctx, variableIDs)
	ret0, _ := ret[0].([]domain.Constraint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByVariableIDs indicates an expected call of ListByVariableIDs.
func (mr *MockconstraintRepositoryMockRecorder) ListByVariableIDs(ctx, variableIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByVariableIDs", reflect.TypeOf((*MockconstraintRepository)(nil).ListByVariableIDs), ctx, variableIDs)
}
