// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -package usecase -source contract.go -destination contract_mock.go
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	domain "github.com/qsoulior/tech-generator/backend/internal/usecase/project_user_list/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockprojectRepository is a mock of projectRepository interface.
type MockprojectRepository struct {
	ctrl     *gomock.Controller
	recorder *MockprojectRepositoryMockRecorder
	isgomock struct{}
}

// MockprojectRepositoryMockRecorder is the mock recorder for MockprojectRepository.
type MockprojectRepositoryMockRecorder struct {
	mock *MockprojectRepository
}

// NewMockprojectRepository creates a new mock instance.
func NewMockprojectRepository(ctrl *gomock.Controller) *MockprojectRepository {
	mock := &MockprojectRepository{ctrl: ctrl}
	mock.recorder = &MockprojectRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockprojectRepository) EXPECT() *MockprojectRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockprojectRepository) GetByID(ctx context.Context, id int64) (*domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockprojectRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockprojectRepository)(nil).GetByID), ctx, id)
}

// MockprojectUserRepository is a mock of projectUserRepository interface.
type MockprojectUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockprojectUserRepositoryMockRecorder
	isgomock struct{}
}

// MockprojectUserRepositoryMockRecorder is the mock recorder for MockprojectUserRepository.
type MockprojectUserRepositoryMockRecorder struct {
	mock *MockprojectUserRepository
}

// NewMockprojectUserRepository creates a new mock instance.
func NewMockprojectUserRepository(ctrl *gomock.Controller) *MockprojectUserRepository {
	mock := &MockprojectUserRepository{ctrl: ctrl}
	mock.recorder = &MockprojectUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockprojectUserRepository) EXPECT() *MockprojectUserRepositoryMockRecorder {
	return m.recorder
}

// GetByProjectID mocks base method.
func (m *MockprojectUserRepository) GetByProjectID(ctx context.Context, projectID int64) ([]domain.ProjectUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProjectID", ctx, projectID)
	ret0, _ := ret[0].([]domain.ProjectUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProjectID indicates an expected call of GetByProjectID.
func (mr *MockprojectUserRepositoryMockRecorder) GetByProjectID(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProjectID", reflect.TypeOf((*MockprojectUserRepository)(nil).GetByProjectID), ctx, projectID)
}
